### ISSUE TITLE
FRONT : Afficher une liste des dépenses

### ISSUE THREAD

**Issue by HighnKein** [the-smaug/app-traveled#109]
![gestion_depenses](https://user-images.githubusercontent.com/9964529/35525434-bc9b5300-0524-11e8-87e1-e6de7ff98b25.png)

**Comment by Oceanwave6** [comment]
![gestion_depenses](https://user-images.githubusercontent.com/9129560/36719737-41412b2e-1ba6-11e8-8fd5-24e9355f3792.png)
