### ISSUE TITLE
FRONT : voir les détails d'un logement

### ISSUE THREAD

**Issue by HighnKein** [the-smaug/app-traveled#118]
![36719697-1f42de6e-1ba6-11e8-9d4e-acf9fc06b922](https://user-images.githubusercontent.com/9964529/36719905-a9f02e9a-1ba6-11e8-8f77-164318cfaffe.png)

**Comment by Oceanwave6** [comment]
![details_logement](https://user-images.githubusercontent.com/9129560/36719697-1f42de6e-1ba6-11e8-9d4e-acf9fc06b922.png)
