### ISSUE TITLE
FRONT : Ajouter / modifier un logement

### ISSUE THREAD

**Issue by the-smaug** [the-smaug/app-traveled#132]
![ajout_modif_logements](https://user-images.githubusercontent.com/9964529/36719803-6a89cb08-1ba6-11e8-9017-d86cd66b4476.png)

**Comment by the-smaug** [comment]
mémo : @HighnKein à compléter

**Comment by Oceanwave6** [comment]
![ajout_modif_logements](https://user-images.githubusercontent.com/9129560/36719630-e01f7b8e-1ba5-11e8-92d1-c75cc6ecb4c2.png)
