### ISSUE TITLE
FRONT : Page connexion

### ISSUE THREAD

**Issue by lmounier** [the-smaug/app-traveled#70]
![Login.png](https://images.zenhubusercontent.com/59e08406b0222d5de47b8371/d617dc48-1fde-430d-968a-ab4df20db63e)Faire le design de la page connexion

**Comment by Oceanwave6** [comment]
Mise à jour maquette.
![login](https://user-images.githubusercontent.com/9129560/35507402-f3719d4a-04ec-11e8-9906-7a0f56fd35f1.png)
