### ISSUE TITLE
FRONT : Page inscription

### ISSUE THREAD

**Issue by lmounier** [the-smaug/app-traveled#71]
Faire le design de la page inscription![inscription.png](https://images.zenhubusercontent.com/59e08406b0222d5de47b8371/5a060f4c-4ecb-4f22-a846-2cca882e9ce7)

**Comment by Oceanwave6** [comment]
Mise à jour maquette.
![inscription](https://user-images.githubusercontent.com/9129560/35506873-1f3928be-04eb-11e8-9420-2049cde24fa4.png)
