### ISSUE TITLE
FRONT : Page Liste des voyages

### ISSUE THREAD

**Issue by lmounier** [the-smaug/app-traveled#72]
Faire le design de la page qui liste tous les voyages d'un utilisateur!

**Comment by Oceanwave6** [comment]
Mise à jour Maquette.
![liste_voyage](https://user-images.githubusercontent.com/9129560/35513173-79b01994-0502-11e8-9064-958ee0419470.png)

**Comment by Oceanwave6** [comment]
Mise à jour maquette.
![liste_voyage](https://user-images.githubusercontent.com/9129560/35513211-9cb23422-0502-11e8-898d-db81f109b3a4.png)
