### ISSUE TITLE
FRONT : Page Menu d'un voyage

### ISSUE THREAD

**Issue by lmounier** [the-smaug/app-traveled#74]
Faire le design de la page d'accueil d'un voyage![Voyage.png](https://images.zenhubusercontent.com/59e08406b0222d5de47b8371/c8774a7f-9a1b-44e4-9ceb-5f549da6f7fe)

**Comment by Oceanwave6** [comment]
Mise à jour de la maquette.
![voyage](https://user-images.githubusercontent.com/9129560/35504470-69fd39b0-04e3-11e8-8637-a6b987ee26cc.png)
