### ISSUE TITLE
FRONT : Page Liste Logement

### ISSUE THREAD

**Issue by lmounier** [the-smaug/app-traveled#75]
Faire le design de la liste des logements 
![Logements.png](https://images.zenhubusercontent.com/59e08406b0222d5de47b8371/2e4c80b8-871d-47e1-9b90-8abab21d69fe)

**Comment by Oceanwave6** [comment]
Mise à jour maquette.
![logements](https://user-images.githubusercontent.com/9129560/35514869-e108c12c-0507-11e8-8a66-428ce1d9bebd.png)
