### ISSUE TITLE
Créer les icônes de l'application 

### ISSUE THREAD

**Issue by lmounier** [the-smaug/app-traveled#95]
- Les 6 icônes de l'accueil d'un voyage
- L'icone "membre"
- L'icone "mail"
- L'icone "password"
- L'icone "adresse"
- L'icone "téléphone"
- L'icone "l'upload"
- L'icone "pdf"

**Comment by Oceanwave6** [comment]
- L’icône d'ajout de fonctionnalités
- L'icône d'ajout de voyageurs
- L'icône plus
- L'icône moins
- L'icône fichier
- L'icône dossier
- L'icône ajouter une personne
