### ISSUE TITLE
FRONT : création d'un voyage 1/4

### ISSUE THREAD

**Issue by HighnKein** [the-smaug/app-traveled#97]
![creation_voyage_1](https://user-images.githubusercontent.com/9964529/35401653-6b14e2d0-01fa-11e8-8a99-94c17e169a30.png)

**Comment by Oceanwave6** [comment]
Mise à jour maquette.
![creation_voyage_1](https://user-images.githubusercontent.com/9129560/35514712-683d7a58-0507-11e8-98f7-ef728d19c195.png)
